### ISSUE TITLE
Add categories to problems

### ISSUE THREAD

**Issue by erikhenrique** [dojopuzzles/dojopuzzles#22]
**As a**

programmer

**I want**

Visualize problems by category

**In order to**

I can choose problems by `mathematics` || `string manipulation` || `difficulty` || `etc`

**Comment by rennerocha** [comment]
We can split this issue in two parts:

- [ ] Allow to set labels/tags/categories to one problem (each problem can have more than one of each)
- [ ] Think a way to allow the user search by this categories in UI.

**Comment by erikhenrique** [comment]
I don't want to continue with this issue anymore in my account. So I will close it.

**Comment by rennerocha** [comment]
You don't need to close the issue. It is a valid and desired feature. You can unsubscribe for notifications, so you won't receive any message about this.

**Comment by erikhenrique** [comment]
Could you please open this issue in your account please?
