### ISSUE TITLE
Upgrade Django version

### ISSUE THREAD

**Issue by rennerocha** [dojopuzzles/dojopuzzles#29]
As the project started almost 10 years ago, and the last change was made 7 years ago, we need to upgrade code for a newer Django version (current is 1.4).

As the models and views that exists are very simple (nothing particularly complex or using advanced Django features), I don't believe it will be too complicated to upgrade it (but probably I am entirely wrong and I have no idea the effort that will be needed).

**Comment by davividal** [comment]
My Django skill are a bit rusty, but I might assist with this as well.

**Comment by rennerocha** [comment]
Closed with https://github.com/dojopuzzles/dojopuzzles/pull/36
