### ISSUE TITLE
Translate source code to english

### ISSUE THREAD

**Issue by rennerocha** [dojopuzzles/dojopuzzles#34]
When the project started, I had no idea how long it would last so I didn't care much about naming things.
As a personal rule, all code that I made now must be written in english, so we need to translate everything in code (class, methods, package names, etc) from portuguese to english.

**Comment by davividal** [comment]
We can use transifex for that.

https://www.transifex.com

I just created an organization there for this project. Message me and I can add you as an administrator there.

**Comment by davividal** [comment]
Maybe you could consider creating subtasks for this issue or splitting this issue into 2?
I mean: one task is extracting all the current text into po files. The other task will be translate everything to English.

**Comment by rennerocha** [comment]
I wasn't planning to translate page content yet, as portuguese is the language for 99.999% of our visitors, so I don't think we need something like `.po` files at this moment.

What I want is to translate class names like `Problema` to `Problem`, or app name from `contribuicao` to `contribution`.

**Comment by davividal** [comment]
I see. Way simpler then.
Still, transitioning to po files should be pretty straightforward.

**Comment by rennerocha** [comment]
As we are rewriting most of the code during migration to Django 3.1, this issue will be accomplished, so there is no need to have it opened.
