### ISSUE TITLE
Redirect problem URLs from old version to new updated version

### ISSUE THREAD

**Issue by leao-nardo** [dojopuzzles/dojopuzzles#50]
ta quebrado todos lins antigos . 
precisa segundo o proprio renne de : " uma view que pega "/problemas/exibe/<slug>" e redireciona para "/problems/<slug>""

**Comment by rennerocha** [comment]
From @leao-nardo :
Old links (before Django update migration) are not valid anymore. This is not good as these links are widespread over the Internet and we don't want them to be broken.

We need to create a new view that redirects URLs with the old format to the new one. For example:
Old URL: http://dojopuzzles.com/problemas/exibe/fizzbuzz
New URL: https://dojopuzzles.com/problems/fizzbuzz

This can be acomplished adding a new URL route that identify the **slug** and redirects to the right URL:
Old URL pattern: `http://dojopuzzles.com/problemas/exibe/<slug>`
New URL pattern: `https://dojopuzzles.com/problems/<slug>`

**slug** is the same in old a new versions, so if you get the slug from old URL, you can use in new URL as well.

**Comment by beingbiplov** [comment]
hey, can I work on this?

**Comment by rennerocha** [comment]
Sure you can!

**Comment by leao-nardo** [comment]
seems like it's already done so i'm closing, right ?
