### ISSUE TITLE
503 Service Temporarily Unavailable: dojopuzzles.com

### ISSUE THREAD

**Issue by ddevdan** [dojopuzzles/dojopuzzles#55]
Something went wrong with the website host.
https://dojopuzzles.com/
![image](https://user-images.githubusercontent.com/42525687/215228398-927be20e-4af5-4107-a86e-617f25b419a6.png)

**Comment by rennerocha** [comment]
Container was down. Probably I closed it wrongly during some changes in my server. It is up and running now.

**Comment by ddevdan** [comment]
> Container was down. Probably I closed it wrongly during some changes in my server. It is up and running now.

Thank you :)
